
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-daisy-com-v1-daisyinstallation
  failurePolicy: Fail
  name: mdaisyinstallation.kb.io
  rules:
  - apiGroups:
    - daisy.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daisyinstallations
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-daisy-com-v1-daisyinstallation
  failurePolicy: Fail
  name: vdaisyinstallation.kb.io
  rules:
  - apiGroups:
    - daisy.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daisyinstallations
  sideEffects: None
