# permissions for end users to view daisyoperatorconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daisyoperatorconfiguration-viewer-role
rules:
- apiGroups:
  - daisy.com.daisy.com
  resources:
  - daisyoperatorconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - daisy.com.daisy.com
  resources:
  - daisyoperatorconfigurations/status
  verbs:
  - get
