# permissions for end users to view daisytemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daisytemplate-viewer-role
rules:
- apiGroups:
  - daisy.com.daisy.com
  resources:
  - daisytemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - daisy.com.daisy.com
  resources:
  - daisytemplates/status
  verbs:
  - get
