apiVersion: "daisy.com/v1"
kind: "DaisyInstallation"
metadata:
  name: "simple02"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  pvReclaimPolicy: Retain
  configuration:
    zookeeper:
      nodes:
        - host: tob44.bigdata.lycc.qihoo.net
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: "/simple01"
    users:
      default/networks/ip:
        - "0.0.0.0/0"
      admin/networks/ip: "::/0"
      admin/password: admin
      admin/profile: default
    settings:
      listen_host: "0.0.0.0"
    clusters:
      cluster:
        name: cluster
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName:  kubevirt-hostpath-provisioner
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: log-volume-template
        spec:
          storageClassName:  kubevirt-hostpath-provisioner
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi