apiVersion: "daisy.com/v1"
kind: "DaisyInstallation"
metadata:
  name: "simple01"
spec:
  pvReclaimPolicy: Retain
  configuration:
    users:
      default/networks/ip:
        - "0.0.0.0/0"
      admin/networks/ip: "::/0"
      admin/password: admin
      admin/profile: default
    settings:
      listen_host: "0.0.0.0"
    clusters:
      cluster:
        name: cluster
        layout:
          shardsCount: 2
          replicasCount:  1