apiVersion: "daisy.com/v1"
kind: "DaisyInstallation"
metadata:
  name: "simple01"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  pvReclaimPolicy: Retain
  configuration:
    users:
      default/networks/ip:
        - "0.0.0.0/0"
    settings:
      listen_host:
        - "0.0.0.0"
    clusters:
      cluster:
        name: cluster
        layout:
          shardsCount: 1
          replicasCount:  1
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: log-volume-template
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi