apiVersion: "daisy.com/v1"
kind: "DaisyInstallation"
metadata:
  name: "simple06"
spec:
  clusterType: "DistributedMergeTree"
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  pvReclaimPolicy: Retain
  configuration:
    kafka:
      nodes:
        - host: tob44.bigdata.lycc.qihoo.net
          port: 9092
    settings:
      listen_host: "0.0.0.0"
    clusters:
      cluster:
        name: cluster
        layout:
          shardsCount: 2
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        metadata:
          name: "simple01"
        spec:
          containers:
            - name: clickhouse
              imagePullPolicy: Always
              image: registry.foundary.zone:8360/dae-dev/daisy-server:dev-k8s
              resources:
                limits:
                  memory: "512Mi"
                  cpu: "0.5"
                requests:
                  memory: "512Mi"
                  cpu: "0.5"
              ports:
                - containerPort: 8123
                  name: http
                  protocol: TCP
                - containerPort: 9000
                  name: tcp
                  protocol: TCP
                - containerPort: 9009
                  name: interserver
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /ping
                  port: 8123
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /ping
                  port: 8123
                  scheme: HTTP
                initialDelaySeconds: 12
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName:  kubevirt-hostpath-provisioner
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      - name: log-volume-template
        spec:
          storageClassName:  kubevirt-hostpath-provisioner
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
